version: '2.2'

services:
  todo-ui:
    image: daomaster/todo-client:latest
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      todo-service:
        condition: service_started

  todo-service:
    image: daomaster/todo-server:latest
    restart: on-failure
    scale: 3
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_SERVER=${MONGO_SERVER}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}